Powershell Get-EventLog -LogName ^* ^| ForEach {Clear-EventLog $_.log}
schtasks /Change /TN "Microsoft\Windows\Management\Provisioning\Logon" /Disable
schtasks /Change /TN "Microsoft\Windows\Management\Provisioning\Cellular" /Disable
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\appcompat\appraiser' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\appcompat\encapsulation' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\DiagTrack' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\DigitalLocker' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Downloaded Program Files' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\GameBarPresenceWriter' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\LastGood.Tmp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\LiveKernelReports' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Logs\waasmedic' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\ModemLogs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Performance' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Panther' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\RemotePackages' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\Setup' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SchCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\appraiser' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\Logs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SysWOW64\Logs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\LogFiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\SysWOW64\LogFiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\sru' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\System32\WCN' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\TAPI' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%WinDir%\tracing' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\AMD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Adobe_backup' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Adobe-Backup' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\InstallShield' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Vault' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\AccountPictures' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Network Shortcuts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Printer Shortcuts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Templates' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Start Menu\Programs\Maintenance' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Microsoft\Windows\Start Menu\Programs\Accessories' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Mozilla\Firefox\Crash Reports' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%AppData%\Mozilla\Firefox\Pending Pings' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Adobe' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\UXP' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Comms' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Coderbag' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\InputPersonalization' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Vault' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows Sidebar' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\ActionCenterCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Application Shortcuts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\CloudStore' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\GameExplorer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\Ringtones' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\RoamingTiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\SettingSync' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\Windows\WER' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Intel' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Diagnosis' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\DiagnosticLogCSP' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\DeviceSync' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\DRM' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\EdgeUpdate' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Event Viewer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\MapData' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\NetFramework' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Provisioning' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Settings' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\SmsRouter' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Spectrum' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Speech_OneCore' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\WDF' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\WinMSIPC' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\WPD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\ClipSVC\Install' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\ClipSVC\Import' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\DeviceMetadataCache' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\GameExplorer' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\LfSvc' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\OneSettings' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Parental Controls' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Power Efficiency Diagnostics' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\RetailDemo' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Ringtones' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\WER' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\wfp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Start Menu\Programs\Maintenance' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\Microsoft\Windows\Start Menu\Programs\Accessibility' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\SoftwareDistribution' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\WindowsHolographicDevices' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\PerfLogs' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\Microsoft' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\AMD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\NVIDIA' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\Intel' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\drivers' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\3D Objects' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\Contacts' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\Links' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%UserProfile%\IntelGraphicsProfiles' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\systemprofile\AppData\Local\PlaceholderTileLogoFolder' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\systemprofile\AppData\Roaming\Leap Motion' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\Journal' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemRoot%\System32\config\RegBack' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramFiles(x86)%\AMD' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramFiles(x86)%\NVIDIA Corporation' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%SystemDrive%\Users\Default\NTUSER.DAT_orig' -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Temp' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\PlaceholderTileLogoFolder' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\EDP' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\Microsoft\NetTraces' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%LocalAppData%\gtk-3.0' -Recurse -Force -EA SilentlyContinue -Verbose"
Powershell -EP Bypass -MTA -NOL -NONI -NOP -C "Remove-Item '%ProgramData%\regid.1991-06.com.microsoft' -Recurse -Force -EA SilentlyContinue -Verbose"
