%SystemRoot%\System32\OneDriveSetup.exe /uninstall
dism /online /Disable-Feature /FeatureName:"MediaPlayback" /Quiet /NoRestart
dism /online /Disable-Feature /FeatureName:"Printing-XPSServices-Features" /Quiet /NoRestart
dism /online /Disable-Feature /FeatureName:"Printing-PrintToPDFServices-Features" /Quiet /NoRestart
dism /online /Disable-Feature /FeatureName:"Printing-Foundation-Features" /Quiet /NoRestart
dism /online /Disable-Feature /FeatureName:"Microsoft-Hyper-V-All" /Quiet /NoRestart
chcp 437>nul
Powershell Get-AppxPackage -allusers ^*Microsoft.People^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Clipchamp.Clipchamp^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Disney.37853FC22B2CE^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.MSPaint^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.Microsoft3DViewer^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.MixedReality.Portal^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.Office.OneNote^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.PowerAutomateDesktop^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.ScreenSketch^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.SkypeApp^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.Todos^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.Wallet^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.WindowsAlarms^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.WindowsCamera^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.WindowsFeedbackHub^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.WindowsMaps^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.WindowsSoundRecorder^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.YourPhone^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.ZuneMusic^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.ZuneVideo^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*MicrosoftCorporationII.QuickAssist^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*SpotifyAB.SpotifyMusic^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.WindowsSoundRecorder^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Getstarted^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Client.WebExperience^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*windowscommunicationsapps^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Paint^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*ScreenSketch^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WindowsCamera^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WindowsStore^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*XboxIdentityProvider^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*XboxGamingOverlay^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WindowsAlarms^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*ZuneVideo^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*ZuneMusic^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*YourPhone^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*XboxSpeechToTextOverlay^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*XboxGameOverlay^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Xbox.TCUI^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WindowsSoundRecorder^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WindowsMaps^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WindowsFeedbackHub^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WebpImageExtension^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*WebMediaExtensions^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*VP9VideoExtensions^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Todos^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*StorePurchaseApp^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*PowerAutomateDesktop^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*MicrosoftStickyNotes^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*MicrosoftSolitaireCollection^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*MicrosoftOfficeHub^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*HEIFImageExtension^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*GetHelp^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*GamingApp^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*BingWeather^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.549981C3F5F10^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*BingNews^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Microsoft.OneDriveSync^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*SpotifyAB.SpotifyMusic^* ^| Remove-AppxPackage
Powershell Get-AppxPackage -allusers ^*Teams^* ^| Remove-AppxPackage
Powershell -ExecutionPolicy Bypass -Command "Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*OutlookForWindows*'} | Remove-AppxPackage"
Powershell Get-WindowsPackage -Online | Where PackageName -like *Hello-Face* | Remove-WindowsPackage -Online -NoRestart
Powershell Get-WindowsPackage -Online | Where PackageName -like *QuickAssist* | Remove-WindowsPackage -Online -NoRestart
chcp 65001>nul
